### ISSUE TITLE
buildMex

### ISSUE THREAD

**Issue by hakimabdulrab** [vkrepo/MATLAB-NS3#3]
dear friend

when i try to run the .m file named buildMex.m in matlab, I get the following error

/home/initNs3Interface.cpp not found; check that you are in the correct current folder, and check the spelling
of '/home/initNs3Interface.cpp'.

can you please help me on how to overcome this issue?

**Comment by vkrepo** [comment]
> dear friend
> 
> when i try to run the .m file named buildMex.m in matlab, I get the following error
> 
> /home/initNs3Interface.cpp not found; check that you are in the correct current folder, and check the spelling
> of '/home/initNs3Interface.cpp'.
> 
> can you please help me on how to overcome this issue?

There are no recent changes in this repository.  The build does not expect the file path '/home/initNs3Interface.cpp'. Ensure that you followed all the steps as in README.

**Comment by hakimabdulrab** [comment]
> > dear friend
> > when i try to run the .m file named buildMex.m in matlab, I get the following error
> > /home/initNs3Interface.cpp not found; check that you are in the correct current folder, and check the spelling
> > of '/home/initNs3Interface.cpp'.
> > can you please help me on how to overcome this issue?
> 
> There are no recent changes in this repository. The build does not expect the file path '/home/initNs3Interface.cpp'. Ensure that you followed all the steps as in README.

I appreciate your reply
i reinstalled and followed the description in README file carefully. however, the issue still exist.
Do i need to modify the buildMex.m file in such a way that it suits with my computer? or what else could be done?
thanks in advance.

**Comment by hakimabdulrab** [comment]
> > > dear friend
> > > when i try to run the .m file named buildMex.m in matlab, I get the following error
> > > /home/initNs3Interface.cpp not found; check that you are in the correct current folder, and check the spelling
> > > of '/home/initNs3Interface.cpp'.
> > > can you please help me on how to overcome this issue?
> > 
> > 
> > There are no recent changes in this repository. The build does not expect the file path '/home/initNs3Interface.cpp'. Ensure that you followed all the steps as in README.
> 
> I appreciate your reply
> i reinstalled and followed the description in README file carefully. however, the issue still exist.
> Do i need to modify the buildMex.m file in such a way that it suits with my computer? or what else could be done?
> thanks in advance.

thank you sir

building was completed successfully
I need to navigate into the folder which contains the buildMex file

**Comment by vkrepo** [comment]
Thank you for informing that it worked for you after navigating into the folder.

**Comment by lag-ops** [comment]
> 亲爱的朋友
> 
> 当我尝试在 matlab 中运行名为 buildMex.m 的 .m 文件时，出现以下错误
> 
> 找不到/home/initNs3Interface.cpp；检查您是否在正确的当前文件夹中，并检查 “/home/initNs3Interface.cpp”的拼写。
> 
> 你能帮我解决这个问题吗？



> > > > dear friend
> > > > when i try to run the .m file named buildMex.m in matlab, I get the following error
> > > > /home/initNs3Interface.cpp not found; check that you are in the correct current folder, and check the spelling
> > > > of '/home/initNs3Interface.cpp'.
> > > > can you please help me on how to overcome this issue?
> > > 
> > > 
> > > There are no recent changes in this repository. The build does not expect the file path '/home/initNs3Interface.cpp'. Ensure that you followed all the steps as in README.
> > 
> > 
> > I appreciate your reply
> > i reinstalled and followed the description in README file carefully. however, the issue still exist.
> > Do i need to modify the buildMex.m file in such a way that it suits with my computer? or what else could be done?
> > thanks in advance.
> 
> thank you sir
> 
> building was completed successfully I need to navigate into the folder which contains the buildMex file

my dear friends, when i try to run the .m file named buildMex.m in matlab, I get the following error
mistaken use mex
/usr/bin/ld: can not find -lmexNs3State
collect2: error: ld returned 1 exit status
Do you meet this problem?
