### ISSUE TITLE
libmexNs3State.so: cannot open shared object file: No such file or directory #1

### ISSUE THREAD

**Issue by WryaM1** [vkrepo/MATLAB-NS3#4]
First thanks to vkrepo for sharing this work. 
I found that this issue was closed but it took me some days to solve it and wanted to share it. For me the following command line solved the problem under Linux Ubuntu 20.04:

$ env LD_LIBRARY_PATH=$HOME/<your path to MATLAB-NS3-master>/MATLAB-NS3-master/ns-allinone-3.29/ns-3.29/build/lib /usr/MATLAB/R2018a/bin/matlab

where in fact the path LD_LIBRARY_PATH is assigned before launching the matlab application.

**Comment by vkrepo** [comment]
Thanks for sharing the solution.  Might be useful for others too...
